<%
var getFiles = function(prop) {return grunt.file.expand({cwd:'.'},grunt.config.get(prop));};
%>//----------------------------------------------------------------------------------------------------------------------
// This is an autogenerated file containing the contents of all the filter javascript for all the systems.
//
// @module systems.filters.js
//----------------------------------------------------------------------------------------------------------------------

var module = angular.module('rpgkeeper.systems.filters', []);

<% _.forEach(getFiles('project.systems.filters'), function(src) { var file = grunt.file.read(src); %>
/* ====================== Begin: <%= src %> ====================== */

<%= file %>

/* ======================  End: <%= src %>  ====================== */
<% }); %>

//----------------------------------------------------------------------------------------------------------------------