<%
var getFiles = function(prop) {return grunt.file.expand({cwd:'.'},grunt.config.get(prop));};
%>//----------------------------------------------------------------------------------------------------------------------
// This is an autogenerated file containing the contents of all the controller javascript for all the systems.
//
// @module systems.widgets.js
//----------------------------------------------------------------------------------------------------------------------

var module = angular.module('rpgkeeper.systems.widgets', []);

<% _.forEach(getFiles('project.systems.widgets'), function(src) { var file = grunt.file.read(src); %>
/* ====================== Begin: <%= src %> ====================== */

<%= file %>

/* ======================  End: <%= src %>  ====================== */
<% }); %>

//----------------------------------------------------------------------------------------------------------------------