services:
  rpgkeeper-old:
    image: morgul/rpgkeeper-v1:latest
    environment:
      GOOGLE_CLIENT_ID: "{{client}}"
      GOOGLE_CLIENT_SECRET: "{{secret}}"
      GOOGLE_CALLBACK_URL: "https://old.rpgkeeper.com/auth/google/callback"
      SESSION_SECRET: "{{sess}}"
    restart: unless-stopped
    volumes:
      - /srv/docker/rpgkeeper-old/db:/app/server/db
      - /srv/docker/rpgkeeper-old/sessions:/app/server/sessions
      - /srv/docker/rpgkeeper-old/systems/eote:/app/systems/eote/db
      - /srv/docker/rpgkeeper-old/systems/generic:/app/systems/generic/db
    ports:
      - "2697:8081"
